---
- name: create user and configure keys
  hosts: all
  user: root
  vars:
    login: liam
  tasks:
    - name: create user
      user:
        name: "{{ login }}"
        shell: /usr/bin/zsh
        append: yes
        groups: sudo

    - name: add authorized keys for "{{ login }}"
      authorized_key:
        user: "{{ login }}"
        key: https://github.com/hut8.keys

- name: install latest software
  hosts: all
  user: "{{ login }}"
  vars:
    login: liam
  tasks:
    - name: clone myself
      git:
        dest: ~/build-machine
        repo: git@github.com:hut8/build-machine
        accept_hostkey: True
        update: True

    - name: clone prezto
      git:
        dest: ~/.zprezto
        repo: git@github.com:hut8/prezto
        accept_hostkey: yes
        update: yes
        recursive: yes

    - name: install prezto
      script: 'install-dotfiles'

    - name: install dotfiles
      file:
        src: ~/build-machine/{{ item }}
        dest: ~/{{ item }}
        state: hard
      with_items:
        - .pryrc
        - .tmux.conf

    - name: install go tools
      script: 'install-go-tools'

    - name: install prelude
      git:
        dest: ~/.emacs.d
        repo: git@github.com:hut8/prelude
        accept_hostkey: yes
        update: yes
        force: yes
