---
- name: create user and configure keys
  hosts: all
  user: root
  tasks:
    - name: create user
      user: name=liam shell=/usr/bin/zsh

    - name: add authorized keys for liam
      authorized_key: user=liam key=https://github.com/hut8.keys

    - copy: src=sudoers
            dest=/etc/sudoers.d/liam
            mode=440

- name: install latest software
  hosts: all
  user: liam
  tasks:
    - name: clone myself
      git:
        dest: ~/build-machine
        repo: git@github.com:hut8/build-machine
        accept_hostkey: True
        update: True

    - name: clone prezto
      git: >-
        dest=~/.zprezto
        repo=git@github.com:hut8/prezto
        accept_hostkey=yes
        update=yes
        recursive=yes

    - name: install prezto
      script: 'install-dotfiles'

    - name: install dotfiles
      file:
        src: ~/build-machine/{{ item }}
        dest: ~/{{ item }}
        state: hard
      with_items:
        - .pryrc
        - .tmux.conf

    - name: install go tools
      script: 'install-go-tools'

    - name: install prelude
      git: >-
        dest=~/.emacs.d
        repo=git@github.com:hut8/prelude
        accept_hostkey=yes
        update=yes
        force=yes

    # - name: retrieve emacs
    #   unarchive:
    #     src: "http://ftp.gnu.org/gnu/emacs/emacs-25.1.tar.gz"
    #     dest: "~/"
    #     remote_src: yes
    #     creates: "~/emacs-25.1"

    # - name: configure and build emacs
    #   shell: >-
    #     ./configure --without-x --without-makeinfo --prefix=$HOME && \
    #     make && \
    #     make install
    #   args:
    #     chdir: ~/emacs-25.1
