#!/bin/bash
# Ubuntu 20.04
set -euo pipefail

if ! [ $(id -u) = 0 ]; then
    echo 'this script must be run as root'
    exit 1
fi

user_exists(){ id "$1" &>/dev/null; }

sudo apt update
sudo apt upgrade -y
sudo apt install -y \
    apt-transport-https \
    autoconf \
    automake \
    build-essential \
    curl \
    dnsutils \
    emacs \
    git \
    gnupg \
    htop \
    iotop \
    jq \
    lsb-release \
    moreutils \
    pcregrep \
    pv \
    python3 \
    python3-dev \
    python3-pip \
    python-is-python3 \
    rsync \
    silversearcher-ag \
    speedometer \
    texinfo \
    tig \
    tmux \
    toilet \
    wget \
    zsh

# Add docker repository and install docker
docker_keyring_path='/usr/share/keyrings/docker-archive-keyring.gpg'
if [ ! -f "$docker_keyring_path" ]; then
    echo "adding docker keyring to $docker_keyring_path"
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
        gpg --dearmor -o "$docker_keyring_path"
fi

docker_source_path='/etc/apt/sources.list.d/docker.list'
docker_source_url='https://download.docker.com/linux/ubuntu'
if [ ! -f $docker_source_path ]; then
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=$docker_keyring_path] $docker_source_url $(lsb_release -cs) stable" > "$docker_source_path"
fi
apt update
apt install -y docker-ce docker-ce-cli containerd.io

# Create my user
if ! user_exists "liam"; then
    echo 'creating user'
    useradd \
        --comment 'Liam' \
        --user-group \
        --shell /usr/bin/zsh \
        --create-home \
        --groups docker
    sudo -u liam mkdir /home/user/.ssh
    sudo -u liam \
         curl https://github.com/hut8.keys > /home/user/.ssh/authorized_keys
    sudo -u liam chmod 0600 /home/user/.ssh/authorized_keys
fi
