#!/usr/bin/zsh
set -euo pipefail
setopt EXTENDED_GLOB

if [[ $(id -u -n) != liam ]]; then
    echo 'must be run as liam'
    exit 1
fi

if [[ $HOME != '/home/liam' ]]; then
  echo "\$HOME=$HOME"
  echo "expected /home/liam"
  exit 1
fi

git config --global pull.rebase false

cd "$HOME" # we don't want RVM to popd into /root

if [[ ! -d "$HOME/build-machine" ]]; then
    git clone \
        https://github.com/hut8/build-machine \
        "$HOME/build-machine"
fi

(
  cd "$HOME/build-machine"
  git pull
)

mkdir -p "$HOME/.ssh"
curl https://github.com/hut8.keys > \
  "$HOME/.ssh/authorized_keys"
chmod 0600 "$HOME/.ssh/authorized_keys"

# Prezto
if [[ ! -d "$HOME/.zprezto" ]]; then
  echo 'installing prezto'
    git clone --recursive \
        https://github.com/hut8/prezto.git \
        "${ZDOTDIR:-$HOME}/.zprezto"

    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
        rm -f "${ZDOTDIR:-$HOME}/.${rcfile:t}"
        ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done
fi

# Go
PATH="/usr/local/go/bin:$PATH"
if type go &> /dev/null;
then
    go install golang.org/x/tools/gopls@latest
    go install honnef.co/go/tools/cmd/staticcheck@latest
fi

# Rust
if [[ ! -d "$HOME/.cargo" ]]; then
  echo 'installing rust'
  curl 'https://sh.rustup.rs' -sSf | sh -s -- -y
  source $HOME/.cargo/env
  rustup component add rls rust-src
fi

# RVM
if [[ ! -d "$HOME/.rvm" ]]; then
  echo 'installing rvm'
  \curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  \curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
  set +u # uncool, rvm...
  cd $HOME
  \curl -sSL https://get.rvm.io | bash -s stable
  source "$HOME/.rvm/scripts/rvm"
  rvm install 3.0
  set -u
fi

# NVM
if [[ ! -f "$HOME/.nvm/nvm.sh" ]]; then
   echo 'installing nvm'
   curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
fi

for f in .sqliterc .tmux.conf .pryrc .p10k.zsh ; do
  echo "linking $f"
  ln "$HOME/build-machine/$f" "$HOME/$f"
done

# emacs
if [[ ! -d "$HOME/.emacs.d/.git" ]]; then
  echo "cloning prelude"
  git clone git@github.com:hut8/prelude "$HOME/.emacs.d"
else
  echo "updating prelude"
  (cd "$HOME/.emacs.d"; git pull)
fi
