#!/usr/bin/zsh
set -euo pipefail
setopt EXTENDED_GLOB

if [[ "$(id -u -n)" -ne "liam" ]]; then
    echo 'must be run as liam'
    exit 1
fi

if [[ ! -d "$HOME/build-machine" ]]; then
    git clone \
        git@github.com:hut8/build-machine \
        "$HOME/build-machine"
fi

mkdir -p "$HOME/.ssh"
curl https://github.com/hut8.keys > 
  "$HOME/.ssh/authorized_keys"
chmod 0600 "$HOME/.ssh/authorized_keys"

# Prezto
if [[ ! -d "$HOME/.zprezto" ]]; then
    git clone --recursive \
        git@github.com:hut8/prezto.git \
        "${ZDOTDIR:-$HOME}/.zprezto"

    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
        rm -f "${ZDOTDIR:-$HOME}/.${rcfile:t}"
        ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done
fi

# RVM
if [[ ! -d "$HOME/.rvm" ]]; then
   \curl -sSL https://rvm.io/mpapis.asc | gpg --import -
   \curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
   \curl -sSL https://get.rvm.io | bash -s stable
fi

# NVM
if [[ ! -f "$HOME/.nvm/nvm.sh" ]]; then
   echo 'installing nvm'
   curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
fi
