#!/bin/bash
# Ubuntu 20.04
# curl -sSL https://raw.githubusercontent.com/hut8/build-machine/master/build-machine-debian | bash
set -euo pipefail

repo_url='https://raw.githubusercontent.com/hut8/build-machine/master'

if ! [ $(id -u) = 0 ]; then
    echo 'this script must be run as root'
    exit 1
fi

export DEBIAN_FRONTEND=noninteractive

user_exists(){ id "$1" &>/dev/null; }

sudo apt update
sudo apt upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
sudo apt install -y \
    -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
    apt-transport-https \
    autoconf \
    automake \
    build-essential \
    cmake \
    curl \
    dnsutils \
    emacs \
    g++ \
    git \
    gnupg \
    htop \
    iotop \
    jq \
    libpq-dev \
    libyaml-dev \
    lsb-release \
    moreutils \
    netcat-openbsd \
    nethogs \
    pcregrep \
    pv \
    python3 \
    python3-dev \
    python3-pip \
    python-is-python3 \
    recode \
    rmlint \
    rsync \
    silversearcher-ag \
    texinfo \
    tig \
    tmux \
    toilet \
    tree \
    wget \
    zsh

hash rclone 2>/dev/null || {
    curl https://rclone.org/install.sh | bash
}


[[ -f /swapfile ]] || {
  dd if=/dev/zero of=/swapfile bs=1024 count=8M
  chmod 0600 /swapfile
  mkswap /swapfile
  swapon /swapfile
}

install -m 0755 -d /etc/apt/keyrings

# Add docker repository and install docker
docker_keyring_path='/etc/apt/keyrings/docker.gpg'
if [ ! -f "$docker_keyring_path" ]; then
    echo "adding docker keyring to $docker_keyring_path"
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
        gpg --dearmor -o "$docker_keyring_path"
    chmod a+r /etc/apt/keyrings/docker.gpg
fi

docker_source_path='/etc/apt/sources.list.d/docker.list'
if [ ! -f $docker_source_path ]; then
    echo \
        "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        tee "$docker_source_path" > /dev/null
fi
apt update
apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Install Go
go_path='/usr/local/go'
go_url_base='https://go.dev/dl'
go_filename='go1.20.3.linux-amd64.tar.gz'
go_url="${go_url_base}/${go_filename}"
if [[ ! -d $go_path ]]; then
    (
        echo "downloading go from $go_url to $go_path"
        cd /tmp
        curl --location --remote-name --silent --show-error "$go_url"
        tar -C /usr/local -xzf "${go_filename}"
        rm "${go_filename}"
    )
fi


# Create my user
if ! user_exists "liam";
then
    echo 'creating user'
    useradd \
        --comment 'Liam' \
        --user-group \
        --shell /usr/bin/zsh \
        --create-home \
        liam
else
    chsh --shell /usr/bin/zsh liam # idempotent
fi

[[ -v "${WITH_DOCKER-}" ]] && usermod -a -G docker liam

# locale-gen en_US.UTF-8 UTF-8
# update-locale en_US.UTF-8 UTF-8

curl -sSL "$repo_url/sudoers" > /etc/sudoers.d/liam

curl -sSL "$repo_url/build-account" |
  sudo --set-home -u liam /usr/bin/zsh
