---
- name: install emacs
  hosts: all
  user: liam
  tasks:
    - name: obtain latest emacs
      git: >-
        dest=/home/liam/emacs
        repo=git://git.sv.gnu.org/emacs.git
        update=yes
        accept_hostkey=yes
        version=tags/emacs-24.5

    - name: configure and build
      shell: >-
        ./autogen.sh && \
        ./configure --without-x --without-makeinfo --prefix=$HOME && \
        make bootstrap && \
        make install
      args:
        chdir: /home/liam/emacs
