#!/bin/bash
set -e
export GOPATH="${HOME}/go"
export PATH="${PATH}:/usr/local/go/bin"
go get -u github.com/nsf/gocode
go get -u github.com/rogpeppe/godef
go get -u github.com/golang/lint/golint
go get -u github.com/lukehoban/go-find-references
go get -u github.com/lukehoban/go-outline
go get -u sourcegraph.com/sqs/goreturns
go get -u golang.org/x/tools/cmd/gorename
