---
- name: install and update packages
  hosts: all
  user: root
  tasks:
    - name: update installed packages
      apt: upgrade=dist update_cache=yes

    - name: install server base packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - apt-file
        - automake
        - autoconf
        - build-essential
        - cowsay
        - curl
        - dnsutils
        - emacs24
        - gettext
        - git
        - htop
        - iotop
        - jq
        - libexpat1-dev
        - libcurl4-openssl-dev
        - libssl-dev
        - moreutils
        - nodejs
        - pcregrep
        - pv
        - python-dev
        - python-pip
        - python3-dev
        - python3-pip
        - rsync
        - silversearcher-ag
        - speedometer
        - texinfo
        - tig
        - tmux
        - toilet
        - wget
        - zsh

- name: install rvm
  hosts: all
  user: root
  roles:
    - role: rvm_io.rvm1-ruby
      rvm1_rubies:
        - 'ruby-2.3.1'

- name: configure keys for root
  hosts: all
  user: root
  tasks:
    - authorized_key: user=root key=https://github.com/hut8.keys
    - authorized_key: user=root key=https://github.com/joshjordan.keys

- name: enable agent forwarding
  hosts: all
  user: root
  tasks:
    - lineinfile: dest=/etc/ssh/sshd_config
                  state=present
                  regexp='^AllowAgentForwarding'
                  line='AllowAgentForwarding yes'
      notify: restart sshd

  handlers:
    - name: restart sshd
      service: name=ssh state=restarted

- name: make swapfile
  hosts: all
  user: root
  roles:
    - { role: kamaln7.swapfile, swapfile_use_dd: True, swapfile_size: 2048 }

- name: install go
  hosts: all
  user: root
  tasks:
    - name: download go binary distribution
      get_url: >-
        dest='/tmp'
        url='https://storage.googleapis.com/golang/go1.7.5.linux-amd64.tar.gz'

    - name: extract tarball
      unarchive: >-
        src=/tmp/go1.7.5.linux-amd64.tar.gz
        dest=/usr/local/
        copy=no
