---
- name: install and update packages
  hosts: all
  user: root
  tasks:
    - name: update installed packages
      apt: upgrade=dist update_cache=yes

    - name: install server base packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - apt-file
        - build-essential
        - cowsay
        - curl
        - dnsutils
        - emacs24
        - gettext
        - git
        - htop
        - iotop
        - jq
        - libcurl4-openssl-dev
        - nodejs
        - pcregrep
        - pv
        - python-dev
        - python-pip
        - python3-dev
        - python3-pip
        - rsync
        - silversearcher-ag
        - speedometer
        - texinfo
        - tig
        - tmux
        - toilet
        - wget
        - zsh

- name: install rvm
  hosts: all
  user: root
  roles:
    - role: rvm_io.rvm1-ruby
      rvm1_rubies:
        - 'ruby-2.2.1'

- name: create user
  hosts: all
  user: root
  tasks:
    - name: create user
      user: name=liam shell=/usr/bin/zsh groups=rvm append=yes

    - name: add authorized keys
      authorized_key: user=liam key=https://github.com/hut8.keys

- name: make swapfile
  hosts: prims
  user: root
  roles:
    - { role: kamaln7.swapfile, swapfile_use_dd: True, swapfile_size: 2048 }
