---
- name: install and update packages
  hosts: all
  user: ubuntu
  become: True
  become_user: root
  tasks:
    - name: update installed packages
      apt: upgrade=dist update_cache=yes

    - name: install server base packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - apt-file
        - automake
        - autoconf
        - build-essential
        - cowsay
        - curl
        - dnsutils
        - emacs24
        - gettext
        - git
        - htop
        - iotop
        - jq
        - libexpat1-dev
        - libcurl4-openssl-dev
        - libssl-dev
        - moreutils
        - nodejs
        - pcregrep
        - pv
        - python-dev
        - python-pip
        - python-setuptools
        - python3-setuptools
        - python3-dev
        - python3-pip
        - rsync
        - silversearcher-ag
        - speedometer
        - texinfo
        - tig
        - tmux
        - toilet
        - wget
        - zsh

    - locale_gen:
        name: en_US.UTF-8
        state: present

- name: install rvm
  hosts: all
  user: ubuntu
  become: True
  become_user: root
  roles:
    - role: rvm_io.ruby
      rvm1_rubies:
        - 'ruby-2.3.1'
      rvm1_user: 'root'

- name: configure machine
  hosts: all
  user: ubuntu
  become: True
  become_user: root
  tasks:
    - authorized_key: user=ubuntu key=https://github.com/hut8.keys
    - lineinfile: dest=/etc/ssh/sshd_config
                  state=present
                  regexp='^AllowAgentForwarding'
                  line='AllowAgentForwarding yes'
      notify: restart sshd
    - lineinfile: dest=/etc/ssh/ssh_config
                  state=present
                  regexp='^StrictHostKeyChecking'
                  line='StrictHostKeyChecking no'
  handlers:
    - name: restart sshd
      service: name=ssh state=restarted

- name: make swapfile
  hosts: all
  user: ubuntu
  become: True
  become_user: root
  roles:
    - { role: kamaln7.swapfile, swapfile_use_dd: True, swapfile_size: 2048 }

- name: install go
  hosts: all
  user: ubuntu
  become: True
  become_user: root
  tasks:
    - name: determine if go is installed
      stat:
        path: /usr/local/go/bin/go
      register: go_stat
    - name: download go binary distribution
      get_url:
        dest: '/tmp'
        url: 'https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz'
      when: go_stat.stat.exists == False

    - name: extract tarball
      unarchive:
        src: "/tmp/go1.8.linux-amd64.tar.gz"
        dest: "/usr/local/"
        copy: no
      when: go_stat.stat.exists == False
