format = """
[ ](bg:9 fg:0)\
$os\
$username\
[](bg:17 fg:9)\
$directory\
[](fg:17 bg:18)\
$git_branch\
$git_status\
[](fg:18 bg:19)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$ruby\
$scala\
[](fg:19 bg:20)\
$docker_context\
[](fg:20 bg:21)\
$time\
[ ](fg:21)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

command_timeout = 5000

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:9"
style_root = "bg:9"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:16"
disabled = true # Disabled by default

[directory]
style = "bg:17"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = ""
style = "bg:19 fg:white"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:20"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = ""
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:18"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:18"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "󰎙"
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = ""
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = ""
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style = "bg:19"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:21"
format = '[ $time ]($style)'
