---
- name: install latest software
  hosts: all
  user: liam
  tasks:
    - name: clone git repository
      git: >-
        dest=~/git
        repo=git@github.com:git/git
        accept_hostkey=yes
        update=yes

    - name: build and install git
      shell: make && make install
      args:
        chdir: ~/git

    - name: clone prezto
      git: >-
        dest=~/.zprezto
        repo=git@github.com:hut8/prezto
        accept_hostkey=yes
        update=yes
        recursive=yes

    - name: install prezto
      script: 'install-dotfiles'

    - name: install dotfiles
      copy: src={{ item }}
            dest=~/{{ item }}
      with_items:
        - .pryrc
        - .tmux.conf

    - name: install prelude
      git: >-
        dest=~/.emacs.d
        repo=git@github.com:hut8/prelude
        accept_hostkey=yes
        update=yes
        force=yes

    - name: retrieve emacs
      unarchive: src=http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz
                 dest=~/
                 creates=~/emacs-24.5
                 copy=no

    - name: configure and build emacs
      shell: >-
        ./configure --without-x --without-makeinfo --prefix=$HOME && \
        make && \
        make install
      args:
        chdir: ~/emacs-24.5
